#include "PatchConfig.h"

#include <fstream>
#include <algorithm>
#include <cctype>
#include <map>
#include <filesystem>
#include <Windows.h>

#include "common.h"

namespace {
    std::map<std::string, bool> g_states;
    bool g_loaded = false;

    // Anchored to this DLL's own directory rather than a relative path, since
    // the process's working directory isn't stable across the module's
    // lifetime - Load() (called very early at startup) and WriteFile() (called
    // later, whenever a checkbox is toggled) were observed resolving "./" to
    // two different real directories, so a saved state written in one session
    // was silently invisible to the next session's Load().
    const std::string& ConfigPath() {
        static std::string path = [] {
            char module_path[MAX_PATH]{};
            HMODULE hModule = nullptr;
            GetModuleHandleExA(
                    GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,
                    reinterpret_cast<LPCSTR>(&ConfigPath), &hModule);
            GetModuleFileNameA(hModule, module_path, MAX_PATH);

            auto dir = std::filesystem::path(module_path).parent_path();
            return (dir / "alpha_ring_patches.cfg").string();
        }();
        return path;
    }

    std::string Trim(const std::string& s) {
        size_t start = s.find_first_not_of(" \t\r\n");
        size_t end   = s.find_last_not_of(" \t\r\n");
        return (start == std::string::npos) ? "" : s.substr(start, end - start + 1);
    }

    std::string MakeKey(const std::string& module, const std::string& patch) {
        std::string key = module + "." + patch;
        std::replace(key.begin(), key.end(), ' ', '_');
        std::transform(key.begin(), key.end(), key.begin(), ::tolower);
        return key;
    }

    void WriteFile() {
        std::ofstream ofs(ConfigPath());
        if (!ofs) return;

        ofs << "# AlphaRing Dev Tools patch states - auto-generated by the game.\n"
               "# Only read at each module's load time, not watched live.\n";

        for (const auto& [key, value] : g_states)
            ofs << key << "=" << (value ? 1 : 0) << "\n";
    }
}

namespace AlphaRing::PatchConfig {
    void Load() {
        if (g_loaded) return;
        g_loaded = true;

        std::ifstream ifs(ConfigPath());
        if (!ifs.is_open()) return;

        std::string line;
        while (std::getline(ifs, line)) {
            auto hash = line.find('#');
            if (hash != std::string::npos) line = line.substr(0, hash);
            line = Trim(line);
            if (line.empty()) continue;

            auto eq = line.find('=');
            if (eq == std::string::npos) continue;

            std::string key = Trim(line.substr(0, eq));
            std::string val = Trim(line.substr(eq + 1));
            std::transform(key.begin(), key.end(), key.begin(), ::tolower);

            g_states[key] = (val == "1" || val == "true");
        }

        LOG_INFO("PatchConfig::Load: loaded {} saved state(s)", g_states.size());
    }

    bool Get(const std::string& module, const std::string& patch, bool& out_value) {
        auto it = g_states.find(MakeKey(module, patch));
        if (it == g_states.end()) return false;
        out_value = it->second;
        return true;
    }

    void Set(const std::string& module, const std::string& patch, bool value) {
        g_states[MakeKey(module, patch)] = value;
        WriteFile();
    }
}
